### ISSUE TITLE
[BUG] ServerError error message instead of "Wrong Level" error message (when in German)

### ISSUE THREAD

**Issue by das-g** [Felienne/hedy#1804]
**Describe the bug**
When you use `echo` in level 2 _in German_, you get the `ServerError` error message instead of the `Wrong Level` error message.

**Paste the Hedy code & level**
Just
```
echo
```
or (with same effect) something more potentially meaningful containing lines beginning with `echo` such as
```
antwort is ask Wie heißt du?
echo Aha, du heißt
```
Level **2**, with **`Deusch`** chosen in the language selector on the top right of the website.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/97746/151079585-910be445-0863-48a7-b139-52b39d271341.png)

> ### Hoppla! Vielleicht haben wir einen kleinen Fehler gemacht.
>
> Du hast ein Programm geschrieben das wir nicht erwartet haben. Wenn du uns hlefen möchtest, dann sende eine Email an hedy@felienne.com und gib darin das Level an in dem du dieses Programm geschrieben hast und füge den Programmcode hinzu. In der Zwischenzeit, probiere aus es ein bisschen anders zu formulieren und schau nochmal in die Beispiele. Danke!

<details><summary>relevant server terminal output (Tracebacks, click to expand)</summary>

```
Traceback (most recent call last):
  File "/app/hedy.py", line 2207, in transpile_inner
    python = transpiler(punctuation_symbols, lookup_table).transform(abstract_syntax_tree)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 130, in transform
    return self._transform_tree(tree)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 126, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 97, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "error_echo_dep_2":

Wrong Level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 469, in parse
    transpile_result = transpile_add_stats(code, level, lang)
  File "/app/app.py", line 539, in transpile_add_stats
    result = hedy.transpile(code, level, lang_)
  File "/app/hedy.py", line 1904, in transpile
    transpile_result = transpile_inner(input_string, level, lang)
  File "/app/hedy.py", line 2216, in transpile_inner
    raise E.orig_exc
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 93, in _call_userfunc
    return f(children)
  File "/app/hedy.py", line 1220, in error_echo_dep_2
    raise hedy.exceptions.WrongLevelException(1,  'echo', "echo_out")
exceptions.WrongLevelException: Wrong Level
INFO:werkzeug:172.17.0.1 - - [26/Jan/2022 00:10:28] "POST /parse HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/app/hedy.py", line 2207, in transpile_inner
    python = transpiler(punctuation_symbols, lookup_table).transform(abstract_syntax_tree)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 130, in transform
    return self._transform_tree(tree)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 126, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 97, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "error_echo_dep_2":

Wrong Level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 469, in parse
    transpile_result = transpile_add_stats(code, level, lang)
  File "/app/app.py", line 539, in transpile_add_stats
    result = hedy.transpile(code, level, lang_)
  File "/app/hedy.py", line 1904, in transpile
    transpile_result = transpile_inner(input_string, level, lang)
  File "/app/hedy.py", line 2216, in transpile_inner
    raise E.orig_exc
  File "/usr/local/lib/python3.9/site-packages/lark/visitors.py", line 93, in _call_userfunc
    return f(children)
  File "/app/hedy.py", line 1220, in error_echo_dep_2
    raise hedy.exceptions.WrongLevelException(1,  'echo', "echo_out")
exceptions.WrongLevelException: Wrong Level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 508, in parse
    response = hedy_error_to_response(ex, hedy_errors)
  File "/app/app.py", line 565, in hedy_error_to_response
    "Error": translate_error(ex.error_code, translations, ex.arguments),
  File "/app/app.py", line 589, in translate_error
    return error_template.format(**arguments)
KeyError: 'original_level'
```

</details>

tl;dr: Root cause seems to be `KeyError: 'original_level'`

**Expected behavior**
The `Wrong Level` error message should be shown instead of the `ServerError` error message. According to https://www.hedycode.com/translate/en/de , that'd currently be

> Das war richtige Hedy-Sprache, aber nicht im richtigen Level. Du hast ein Sprachelement aus Level 1 in Level 2 verwendet.

**What machine and browser you were using (optional)**
Browser: Firefox 96.0.1 (64-bit)

Output of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.92, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre347261.6d8215281b2, nixos-unstable-21.03pre257780.e9158eca70a"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Reproduced on https://www.hedycode.com/hedy/2 and locally with the Docker instructions on 025068018d0bdfea0ddcd16962e8ef3a4fcba36b.

**Comment by das-g** [comment]
This problem seems to have been introduced with 0efaed66d941a6a411af700d099f6e308b89d987. Maybe old placeholder values should be deprecated but not removed, until translations still using them have been updated?

**Comment by Felienne** [comment]
Ah interesting issue! This instance is relatively easy to fix by updating the error pattern (thanks for the good detective work!), but the real issue is to: 

* Somehow test consistency between exceptions and related error messages
* Keep all languages the same (even if that means overriding existing translations with the new and correct En) or as you suggest allow keys to be not used in translations

**Comment by das-g** [comment]
> […] or as you suggest allow keys to be not used in translations

`original_level` seems to be a key used by the translation, not by the (current) English original. I guess a translation _not_ using a key is already possible without any (technical) problems. The problem here seems to be that the translation attempts to use a key that is no longer around (and probably was removed because the English original no longer needed it).

**Comment by Felienne** [comment]
> > […] or as you suggest allow keys to be not used in translations
> 
> `original_level` seems to be a key used by the translation, not by the (current) English original. I guess a translation _not_ using a key is already possible without any (technical) problems. The problem here seems to be that the translation attempts to use a key that is no longer around (and probably was removed because the English original no longer needed it).

Yes that is exactly the issue!

**Comment by boryanagoncharenko** [comment]
Sorry for picking this up after so much time. I am not sure how I missed this issue. Created a PR with a test checking all HedyException subclasses against all languages.
