### ISSUE TITLE
Internal error when code is only a single newline

### ISSUE THREAD

**Issue by bjorn3** [Felienne/hedy#833]
It should give a nice error message like an empty input, but it forwards the python exception "tuple index out of range":

```
Traceback (most recent call last):
  File "~/hedy/hedy.py", line 1098, in transpile
    transpile_result = transpile_inner(input_string, level, sub)
  File "~/hedy/hedy.py", line 1247, in transpile_inner
    program_root = parser.parse(input_string+ '\n').children[0]  # getting rid of the root could also be done in the transformer would be nicer
  File "~/hedy/.env/lib/python3.7/site-packages/lark/lark.py", line 561, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "~/hedy/.env/lib/python3.7/site-packages/lark/parser_frontends.py", line 107, in parse
    return self.parser.parse(stream, start, **kw)
  File "~/hedy/.env/lib/python3.7/site-packages/lark/parsers/earley.py", line 306, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
        * _ASK
        * _EOL
        * _SPACE
        * _PRINT
        * __ANON_1
        * _ECHO
        * _ECHO
        * _ASK
        * _TURN
        * _TURN
        * _FORWARD
        * _PRINT
        * _FORWARD


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/hedy/app.py", line 286, in parse
    transpile_result = hedy.transpile(code, level, sublevel)
  File "~/hedy/hedy.py", line 1104, in transpile
    if E.args[0] == 'Parse':
IndexError: tuple index out of range
error transpiling
```

**Comment by bjorn3** [comment]
I think this can be fixed by making the grammar allow empty programs and then give an error when the parser output is an empty program, instead of comparing the program text with an empty string.
